spring.application.name=etl-off

# Datasource PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/TON_DB
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Server
server.port=8082
